; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
    LIST P=16F887
    #INCLUDE "p16f887.inc"

RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    MAIN                   ; go to beginning of program
    ORG 0x04
	GOTO RUTINA_INTERR;
	
MIS_VARIABLES UDATA_SHR
TEMP_W RES 1
TEMP_STATUS RES 1
BANDERAS RES 1;REGISRO DE MIS BANDERAS EN POSICION 0:ADC,1:TMR0(250MS),2:1SEG,3:UART 
VALOR_ADC RES 1
REGRE_DE_4 RES 1
 
MI_ADC_F EQU 0
MI_TMR0_F EQU 1
MI_1SEC_F EQU 2
 
; TODO ADD INTERRUPTS HERE IF USED

MAIN_PROG CODE                      ; let linker place main program

CONFIG_ADC:
    BANKSEL TRISA
    MOVLW B'00000001';PONE RA0 COMO ENTRADA
    IORWF TRISA;
    MOVLW B'00001110';CERO JUSTIFICA A LA IZQUIERDA Y PONGO 1110 PARA QUE SOLO RA0 SEA ANALOGICA
    MOVWF ADCON1;
    ;HABILITO LA INTERRUPCION POR ADC
    BSF PIE1, ADIE;
    BCF PIE1, ADIF;
    BSF INTCON, PEIE;
    BSF INTCON, GIE;
    BANKSEL ADCON0;
    MOVLW B'11000001'; 11 CLOCK FRC, 000 CANAL0, 1 ENCENDIDO
    MOVWF ADCON0
    CALL ESPERA_11_5US; TIEMPO MINIMO DESDE LA CONFIG HSATA QUE PUEDE CONVERTIR
    BSF ADCON0, GO; QUE ARRANQUE A CONVERTIR
    RETURN
CONFIG_TIMER0:
    ;CALCULOS PARA OSCILADOR EN 1MHZ
    BANKSEL STATUS;
    MOVLW B'00101111';MODO CONTADOR,FLACO DE SUBIDA,PRESCALER EN 256
    MOVWF OPTION_REG;
    BANKSEL INTCON;
    ;HABILITAMOS LAS INTERRUPCIONES PARA EL TIMER0
    BSF INTCON, T0IE;
    BSF INTCON, GIE;
    MOVLW .14;VALOR CALCULADO PARA CONSEGUIR INTERRUPCIONES CADA 250MILIS
    MOVWF TMR0;
    MOVLW .4;
    MOVWF REGRE_DE_4;
    RETURN;
    
CONFIGURAR:
    CALL CONFIG_ADC;
    CALL CONFIG_TIMER0;

ESPERA_11_5US:
    RETURN;
    
RUTINA_INTERR:
    MOVWF TEMP_W
    SWAPF STATUS, W
    MOVWF TEMP_STATUS
    
    BTFSC PIR1, ADIF;SALTO EL ADC?
    BSF BANDERAS, MI_ADC_F;LEVANTO MI BANDERA ADC
    BTFSC INTCON, T0IF;
    BSF BANDERAS, MI_TMR0_F;LEVANTO MI BANDERA TMR0
    
    
    SWAPF TEMP_STATUS, W
    MOVWF STATUS
    SWAPF TEMP_W, F
    SWAPF TEMP_W, W
    
    ;BCF PIR1, ADIF; LIMPIO EL FLAG DE INT DEL ADC
    RETFIE
    
CONV_ADC:
    MOVF ADRESL,W;
    MOVWF VALOR_ADC;
    BCF PIR1, ADIF; LIMPIO EL FLAG DE INT DEL ADC PORQ HAY QUE HACER LO MINIMO POSIBLE EN LA RUTINA DE INT.
    BSF ADCON0, GO; YA TE LEÍ ARRANCA A CONVERTIR EL PROXIMO VALOR
    BCF BANDERAS,MI_ADC_F;BAJO MI BANDERA DEL ADC
    RETURN
PASARON_250M:
    MOVLW .14;
    MOVWF TMR0;
    DECFSZ REGRE_DE_4, F;
    RETURN
    BSF BANDERAS, MI_1SEC_F;LEVANTO MI BANDERA DE 1SEG
    MOVLW .4;
    MOVWF REGRE_DE_4;
    BCF INTCON, T0IF;
    BCF BANDERAS, MI_TMR0_F;BAJO MI BANDERA DEL TIMER0
    RETURN;
    
PASO_UN_SEG:
    ;ACA TENGO QUE COMENZAR LA CONVERSION
    BCF BANDERAS, MI_1SEC_F;BAJO MI BANDERA DE 1SEG
    RETURN
    
MAIN
    CALL CONFIGURAR;
LOOP
    BTFSC BANDERAS, MI_ADC_F;SI SALTO LA BANDERA DEL ADC ENTONCES REVISO LA CONVERSION
    CALL CONV_ADC;
    BTFSC BANDERAS, MI_TMR0_F;SI SALTO LA BANDERA DEL TIMER CADA 250 MILISEC
    CALL PASARON_250M;
    BTFSC BANDERAS, MI_1SEC_F;SI SALTO LA BANDERA CUANDO PASO 1 SEG.
    CALL PASO_UN_SEG;
    GOTO LOOP;
    

    END

    




    
   