; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
    LIST P=16F887
    #INCLUDE "p16f887.inc"

RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    MAIN                   ; go to beginning of program
    ORG 0x04
	GOTO RUTINA_INTERR;
	
MIS_VARIABLES UDATA_SHR
TEMP_W RES 1
TEMP_STATUS RES 1
BANDERAS RES 1;REGISRO DE MIS BANDERAS EN POSICION 0:ADC,1:TMR0(250MS),2:1SEG,3:UART 
VALOR_ADC_H RES 1
VALOR_ADC_L RES 1
REGRE_DE_240 RES 1
CANT_MEDICIONES RES 1
REGRE_BUFFER RES 1
CORTAR_ENVIO RES 1
 
MI_ADC_F EQU 0
MI_TMR0_F EQU 1
MI_1MIN_F EQU 2
MI_BUF_COMPL EQU 3
MI_ENVIO8B_F EQU 4
MI_ENVIO_EN_PROG EQU 5; Que nadie toque el buffer porque lo estoy transmitiendo!!!
MI_ENVIO_COMPLETADO EQU 6;
 
; TODO ADD INTERRUPTS HERE IF USED

MAIN_PROG CODE                      ; let linker place main program

CONFIG_ADC:
    BANKSEL TRISA
    MOVLW B'00000001';PONE RA0 COMO ENTRADA
    IORWF TRISA;
    MOVLW B'00001110';CERO JUSTIFICA A LA IZQUIERDA Y PONGO 1110 PARA QUE SOLO RA0 SEA ANALOGICA
    MOVWF ADCON1;
    ;HABILITO LA INTERRUPCION POR ADC
    BSF PIE1, ADIE;
    BCF PIE1, ADIF;
    BSF INTCON, PEIE;
    BSF INTCON, GIE;
    BANKSEL ADCON0;
    MOVLW B'11000001'; 11 CLOCK FRC, 000 CANAL0, 1 ENCENDIDO
    MOVWF ADCON0
    CALL ESPERA_11_5US; TIEMPO MINIMO DESDE LA CONFIG HSATA QUE PUEDE CONVERTIR
    ;BSF ADCON0, GO; QUE ARRANQUE A CONVERTIR
    RETURN
    
CONFIG_TIMER0:
    ;CALCULOS PARA OSCILADOR EN 1MHZ
    BANKSEL STATUS;
    MOVLW B'00101111';MODO CONTADOR,FLACO DE SUBIDA,PRESCALER EN 256
    MOVWF OPTION_REG;
    BANKSEL INTCON;
    ;HABILITAMOS LAS INTERRUPCIONES PARA EL TIMER0
    BSF INTCON, T0IE;
    BSF INTCON, GIE;
    MOVLW .14;VALOR CALCULADO PARA CONSEGUIR INTERRUPCIONES CADA 250MILIS
    MOVWF TMR0;
    MOVLW .240;
    MOVWF REGRE_DE_240;
    RETURN;

CONFIG_UART:
    ;necesito poner laa uart en modo transmision con una vel de 10417 baudios.
    ; SPBRG = INT(CLOCK/(F*V_DESEADA)-1)
    ; BRobt = CLOCK/(Fx(SPBRG+1))
    ; SPBRG = INT(1M/(64*10417)-1)= 0
    ; SPBRG = INT(1M/(16*10417)-1)= 5
    ; BRobt = 1M/(16x(5+1))= 10416.66 OK!
    ; F=64 BRGH=0, F=16 BRGH=1 
    BSF TXSTA,BRGH; F=16
    BCF TXSTA,SYNC; ASINCRONO
    BSF RCSTA,SPEN; HABILITA el puerto serie
    BSF TXSTA,TXEN; HABILITA la transmision
    BCF TXSTA,TX9; Solo voy a mandar de a 8 bits
    MOVLW .5;
    MOVWF SPBRG;
    BSF INTCON, GIE;
    BSF INTCON, PEIE;
    BSF PIE1, TXIE;
    RETURN;
    
CONFIGURAR:
    MOVLW 0xA0;
    MOVWF FSR;
    MOVLW .10;
    MOVWF CANT_MEDICIONES;
    MOVLW .20;
    MOVWF REGRE_BUFFER;
    CLRF CORTAR_ENVIO;
    
    CALL CONFIG_ADC;
    CALL CONFIG_TIMER0;
    CALL CONFIG_UART;

ESPERA_11_5US:
    RETURN;
    
RUTINA_INTERR:
    MOVWF TEMP_W
    SWAPF STATUS, W
    MOVWF TEMP_STATUS
    
    
    BTFSC INTCON, T0IF;salta cuando pasan 250ms
    CALL PASARON_250M;
    
    BTFSC PIR1, ADIF;SALTO EL ADC?
    CALL CONVERSION_DISP;
    
    BTFSC PIR1, TXIF;salta cuando termina de transmitir ultimos 8bit
    CALL ENVIAR_PROX_8BITS;
    
    
    SWAPF TEMP_STATUS, W
    MOVWF STATUS
    SWAPF TEMP_W, F
    SWAPF TEMP_W, W
    
    ;BCF PIR1, ADIF; LIMPIO EL FLAG DE INT DEL ADC
    RETFIE
    
    
GUARDAR_EN_BUFF:
    ;Vamos a guardar 10 pares por medicion osea un total de 20 registros de la mem.
    MOVFW VALOR_ADC_H;
    MOVWF INDF;
    INCF FSR;
    MOVFW VALOR_ADC_L;
    MOVWF INDF;
    INCF FSR;
    DECFSZ CANT_MEDICIONES;
    RETURN;
    ;tengo el bufer lleno
    CLRF CORTAR_ENVIO;
    CALL ENVIAR_BUF_POR_UART
    RETURN;
    
    
CONVERSION_DISP:
    BCF PIR1, ADIF;
    ;ADRESH                ADRESL
    ;[_ _ _ _ _ _ B B] [B B B B B B B B]
    ; 0 0 0 0 0 0 0 0   0 0 0 0 0 0 0 0 minimo 0v 0 grados
    ; 0 0 0 0 0 0 0 1   0 0 0 0 0 0 0 0 minimo 0v 7.5grados
    ; 0 0 0 0 0 0 1 0   0 0 0 0 0 0 0 0 minimo 0v 15 grados
    ; 0 0 0 0 0 0 1 1   1 1 1 1 1 1 1 1 maximo 5v 30grados
    
    BTFSS ADRESH, 1; verificamos si medimos >=15grados
    RETURN;
    ;laburo
    MOVF ADRESL,W;
    MOVWF VALOR_ADC_L;
    MOVF ADRESH,W;
    MOVWF VALOR_ADC_H;
     
    CALL GUARDAR_EN_BUFF;
    RETURN
    
PASARON_250M:
    BCF INTCON, T0IF;limpio bandera timer
    MOVLW .14;
    MOVWF TMR0;cargo el valor del timer para que cuente los prox 250ms
    
    DECFSZ REGRE_DE_240, F;determinamos que 240*250ms=1min
    RETURN
    ;en este punto paso 1MIN
    MOVLW .240;
    MOVWF REGRE_DE_240;restablece el valor del regresivo
    
    CALL PASO_UN_MIN;
    
    RETURN;

    
ENVIAR_BUF_POR_UART:
    MOVLW .10;
    MOVWF CANT_MEDICIONES;restaruo el valor de la cant de med que necesito en el bufer
    MOVLW 0xA0; cuando esta lleno el buffer FSR apunta al final osea dir 0xB4
    MOVWF FSR;restaruo ek valor del puntero al buffer
    CALL ENVIAR_PROX_8BITS;
    RETURN;

ENVIAR_PROX_8BITS:
    BCF PIR1, TXIF;
    BTFSC CORTAR_ENVIO,0;
    RETURN;
    MOVFW INDF;
    MOVWF TXREG;
    INCF FSR;
    DECFSZ REGRE_BUFFER;
    RETURN;
    ;ya termine de mandar todo el bufer
    MOVLW .1;
    MOVWF CORTAR_ENVIO;
    
    
PASO_UN_MIN:
    ;ACA TENGO QUE COMENZAR LA CONVERSION
    BSF ADCON0,GO;
    RETURN
    
MAIN
    CALL CONFIGURAR;
LOOP
    GOTO LOOP;
    END